/** Step-Audio-EditX 官方 speaking style 可用标签。 */
window.StepAudioEditXSpeakingStyleTags = Object.freeze([
    { key: 'serious', value: 'Speaking in a serious or solemn manner' },
    { key: 'arrogant', value: 'Speaking in an arrogant manner' },
    { key: 'child', value: 'Speaking in a childlike manner' },
    { key: 'older', value: 'Speaking in an elderly-sounding manner' },
    { key: 'girl', value: 'Speaking in a light, youthful feminine manner' },
    { key: 'pure', value: 'Speaking in a pure, innocent manner' },
    { key: 'sister', value: 'Speaking in a mature, confident feminine manner' },
    { key: 'sweet', value: 'Speaking in a sweet, lovely manner' },
    { key: 'exaggerated', value: 'Speaking in an exaggerated, dramatic manner' },
    { key: 'ethereal', value: 'Speaking in a soft, airy, dreamy manner' },
    { key: 'whisper', value: 'Speaking in a whispering, very soft manner' },
    { key: 'generous', value: 'Speaking in a hearty, outgoing, and straight-talking manner' },
    { key: 'recite', value: 'Speaking in a clear, well-paced, poetry-reading manner' },
    { key: 'act_coy', value: 'Speaking in a sweet, playful, and endearing manner' },
    { key: 'warm', value: 'Speaking in a warm, friendly manner' },
    { key: 'shy', value: 'Speaking in a shy, timid manner' },
    { key: 'comfort', value: 'Speaking in a comforting, reassuring manner' },
    { key: 'authority', value: 'Speaking in an authoritative, commanding manner' },
    { key: 'chat', value: 'Speaking in a casual, conversational manner' },
    { key: 'radio', value: 'Speaking in a radio-broadcast manner' },
    { key: 'soulful', value: 'Speaking in a heartfelt, deeply emotional manner' },
    { key: 'gentle', value: 'Speaking in a gentle, soft manner' },
    { key: 'story', value: 'Speaking in a narrative, audiobook-style manner' },
    { key: 'vivid', value: 'Speaking in a lively, expressive manner' },
    { key: 'program', value: 'Speaking in a show-host/presenter manner' },
    { key: 'news', value: 'Speaking in a news broadcasting manner' },
    { key: 'advertising', value: 'Speaking in a polished, high-end commercial voiceover manner' },
    { key: 'roar', value: 'Speaking in a loud, deep, roaring manner' },
    { key: 'murmur', value: 'Speaking in a quiet, low manner' },
    { key: 'shout', value: 'Speaking in a loud, sharp, shouting manner' },
    { key: 'deeply', value: 'Speaking in a deep and low-pitched tone' },
    { key: 'loudly', value: 'Speaking in a loud and high-pitched tone' }
]);
